[package]
name = "guardian-nft"
version = "0.1.0"
description = "Arcanea guardian-nft Anchor program"
edition = "2021"
rust-version = "1.79"
license = "MIT"

[lib]
crate-type = ["cdylib", "lib"]
name = "guardian_nft"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = { version = "=0.31.1" }
